# -*- coding: utf-8 -*-
"""app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ds0yVIT_xmsKFdIL4Tm2E8Mt1D4KutbS
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# import numpy as np
# from streamlit_option_menu import option_menu
# 
# # ====================================
# # PAGE CONFIG
# # ====================================
# 
# st.set_page_config(
#     page_title="Finance Intelligence",
#     page_icon="💰",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# # ====================================
# # PREMIUM CSS
# # ====================================
# 
# st.markdown("""
# <style>
# 
# /* Main background */
# .stApp {
#     background-color: #F6F8FC;
# }
# 
# /* Remove default padding */
# .block-container {
#     padding-top: 2rem;
#     padding-bottom: 2rem;
#     padding-left: 3rem;
#     padding-right: 3rem;
# }
# 
# /* Sidebar */
# [data-testid="stSidebar"] {
#     background: white;
#     border-right: 1px solid #EAEAEA;
# }
# 
# /* Title */
# .main-title {
#     font-size: 42px;
#     font-weight: 700;
#     color: #111827;
# }
# 
# .subtitle {
#     color: #6B7280;
#     font-size: 16px;
#     margin-bottom: 30px;
# }
# 
# /* KPI Cards */
# .metric-card {
#     background: white;
#     border-radius: 24px;
#     padding: 25px;
#     box-shadow: 0px 8px 25px rgba(0,0,0,0.06);
#     border: 1px solid #F1F1F1;
# }
# 
# /* Insight cards */
# .insight-card {
#     background: white;
#     padding: 22px;
#     border-radius: 22px;
#     box-shadow: 0px 4px 15px rgba(0,0,0,0.05);
#     margin-bottom: 15px;
# }
# 
# /* Chart containers */
# .chart-card {
#     background: white;
#     border-radius: 24px;
#     padding: 20px;
#     box-shadow: 0px 4px 18px rgba(0,0,0,0.05);
# }
# 
# /* Recommendation box */
# .recommend-box {
#     background: linear-gradient(
#         135deg,
#         #EEF4FF,
#         #FFFFFF
#     );
# 
#     padding: 18px;
#     border-radius: 18px;
#     margin-bottom: 12px;
#     border-left: 5px solid #2563EB;
# }
# 
# </style>
# """, unsafe_allow_html=True)
# 
# # ====================================
# # HEADER
# # ====================================
# 
# st.markdown(
#     """
#     <div class='main-title'>
#     💰 Personal Finance Intelligence
#     </div>
# 
#     <div class='subtitle'>
#     AI-powered spending intelligence dashboard
#     </div>
#     """,
#     unsafe_allow_html=True
# )
# 
# # ====================================
# # SIDEBAR
# # ====================================
# 
# with st.sidebar:
# 
#     st.markdown("## Navigation")
# 
#     selected = option_menu(
#         menu_title=None,
#         options=[
#             "Overview",
#             "Analytics",
#             "Behavior",
#             "Recommendations"
#         ],
#         icons=[
#             "house",
#             "bar-chart",
#             "activity",
#             "lightbulb"
#         ],
#         default_index=0
#     )
# 
#     st.markdown("---")
# 
#     uploaded_file = st.file_uploader(
#         "Upload CSV",
#         type=["csv"]
#     )
# 
# # ====================================
# # IF NO FILE
# # ====================================
# 
# if uploaded_file is None:
# 
#     st.info(
#         "Upload a financial transaction CSV file to begin."
#     )
# 
#     st.stop()
# 
# # ====================================
# # LOAD DATA
# # ====================================
# 
# df = pd.read_csv(uploaded_file)
# 
# df.columns = (
#     df.columns
#     .str.lower()
#     .str.strip()
# )
# 
# df.drop_duplicates(inplace=True)
# 
# # Date cleaning
# if 'date' in df.columns:
#     df['date'] = pd.to_datetime(
#         df['date'],
#         errors='coerce'
#     )
# 
# # ====================================
# # FEATURES
# # ====================================
# 
# if 'hour' in df.columns:
# 
#     def spending_time(hour):
# 
#         if hour < 12:
#             return "Morning"
# 
#         elif hour < 17:
#             return "Afternoon"
# 
#         elif hour < 21:
#             return "Evening"
# 
#         return "Night"
# 
#     df['time_period'] = (
#         df['hour']
#         .apply(spending_time)
#     )
# 
# # ====================================
# # KPI VALUES
# # ====================================
# 
# total_spending = (
#     df['amount'].sum()
# )
# 
# avg_spending = (
#     df['amount'].mean()
# )
# 
# highest_expense = (
#     df['amount'].max()
# )
# 
# transaction_count = len(df)
# 
# # ====================================
# # PAGE 1 OVERVIEW
# # ====================================
# 
# if selected == "Overview":
# 
#     st.subheader("Financial Overview")
# 
#     c1, c2, c3, c4 = st.columns(4)
# 
#     c1.metric(
#         "💸 Total Spending",
#         f"₹{round(total_spending)}"
#     )
# 
#     c2.metric(
#         "📈 Avg Spend",
#         f"₹{round(avg_spending)}"
#     )
# 
#     c3.metric(
#         "🔥 Highest Expense",
#         f"₹{round(highest_expense)}"
#     )
# 
#     c4.metric(
#         "🧾 Transactions",
#         transaction_count
#     )
# 
#     st.markdown("### Dataset Preview")
# 
#     st.dataframe(
#         df.head(10),
#         use_container_width=True
#     )
# 
# # ====================================
# # ANALYTICS PAGE
# # ====================================
# 
# elif selected == "Analytics":
# 
#     st.subheader(
#         "Spending Analytics"
#     )
# 
#     col1, col2 = st.columns(2)
# 
#     if 'category' in df.columns:
# 
#         category_data = (
#             df.groupby('category')
#             ['amount']
#             .sum()
#             .reset_index()
#         )
# 
#         fig1 = px.bar(
#             category_data,
#             x='category',
#             y='amount',
#             title="Category Spending"
#         )
# 
#         col1.plotly_chart(
#             fig1,
#             use_container_width=True
#         )
# 
#     if 'merchant' in df.columns:
# 
#         merchant_data = (
#             df.groupby('merchant')
#             ['amount']
#             .sum()
#             .reset_index()
#             .sort_values(
#                 by='amount',
#                 ascending=False
#             )
#             .head(10)
#         )
# 
#         fig2 = px.bar(
#             merchant_data,
#             x='merchant',
#             y='amount',
#             title="Top Merchants"
#         )
# 
#         col2.plotly_chart(
#             fig2,
#             use_container_width=True
#         )
# 
#     if 'date' in df.columns:
# 
#         daily = (
#             df.groupby('date')
#             ['amount']
#             .sum()
#             .reset_index()
#         )
# 
#         fig3 = px.line(
#             daily,
#             x='date',
#             y='amount',
#             markers=True,
#             title="Daily Spending Trend"
#         )
# 
#         st.plotly_chart(
#             fig3,
#             use_container_width=True
#         )
# 
# # ====================================
# # BEHAVIOR PAGE
# # ====================================
# 
# elif selected == "Behavior":
# 
#     st.subheader(
#         "Behavioral Analytics"
#     )
# 
#     if 'hour' in df.columns:
# 
#         df['impulsive'] = (
#             (df['hour'] >= 22)
#             |
#             (df['amount'] > 700)
#         )
# 
#         impulsive_count = (
#             df['impulsive']
#             .sum()
#         )
# 
#         st.metric(
#             "⚠️ Impulsive Purchases",
#             impulsive_count
#         )
# 
#         fig4 = px.pie(
#             df,
#             names='impulsive',
#             title="Impulsive Spending"
#         )
# 
#         st.plotly_chart(
#             fig4,
#             use_container_width=True
#         )
# 
# # ====================================
# # RECOMMENDATIONS
# # ====================================
# 
# elif selected == "Recommendations":
# 
#     st.subheader(
#         "Smart Recommendations"
#     )
# 
#     recommendations = []
# 
#     if avg_spending > 700:
# 
#         recommendations.append(
#             "💡 Your spending is relatively high. Consider setting a monthly spending cap."
#         )
# 
#     if 'merchant' in df.columns:
# 
#         top_merchant = (
#             df.groupby('merchant')
#             ['amount']
#             .sum()
#             .idxmax()
#         )
# 
#         recommendations.append(
#             f"🛍️ Highest spending occurs at {top_merchant}. Consider monitoring expenses there."
#         )
# 
#     if len(recommendations) == 0:
# 
#         st.success(
#             "Healthy spending pattern detected."
#         )
# 
#     else:
# 
#         for rec in recommendations:
# 
#             st.markdown(
#                 f"""
#                 <div class='recommend-box'>
#                 {rec}
#                 </div>
#                 """,
#                 unsafe_allow_html=True
#             )