# -*- coding: utf-8 -*-
"""financeTrack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10QCdusUKrhuqgFm965Jx5GREesa1lphz
"""

import pandas as pd

# Load dataset
df = pd.read_csv('/content/transactions.csv')

# Show first 5 rows
df.head()

df.shape

df.columns

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df['category'].value_counts()

df['amount'].mean()

df['amount'].max()

df['amount'].min()

df['amount'].sum()

df.groupby('category')['amount'].sum()

df['payment_method'].value_counts()

df.groupby('day_type')['amount'].sum()

late_night = df[df['hour'] >= 22]
late_night

late_night['amount'].sum()

clean_df = df.copy()

clean_df.isnull().sum()

clean_df.duplicated().sum()

clean_df.dtypes

clean_df['date'] = pd.to_datetime(clean_df['date'])

clean_df.dtypes

clean_df['month'] = clean_df['date'].dt.month

clean_df['day_name'] = clean_df['date'].dt.day_name()

clean_df['is_weekend'] = clean_df['day_name'].isin(['Saturday', 'Sunday'])

def spending_time(hour):
    if hour < 12:
        return 'Morning'
    elif hour < 17:
        return 'Afternoon'
    elif hour < 21:
        return 'Evening'
    else:
        return 'Night'

clean_df['time_period'] = clean_df['hour'].apply(spending_time)

clean_df.head()

clean_df.to_csv('clean_transactions.csv', index=False)

clean_df.groupby('time_period')['amount'].sum()

clean_df.groupby('day_name')['amount'].sum()

clean_df.groupby('merchant')['amount'].sum().sort_values(ascending=False)

clean_df.groupby('is_weekend')['amount'].mean()

clean_df[clean_df['amount'] > 1000]

clean_df['high_spend'] = clean_df['amount'] > 1000

clean_df['high_spend'].value_counts()

clean_df.to_csv('finance_cleaned_v1.csv', index=False)

import matplotlib.pyplot as plt
import plotly.express as px

category_spending = clean_df.groupby('category')['amount'].sum().reset_index()

fig = px.bar(
    category_spending,
    x='category',
    y='amount',
    title='Total Spending by Category'
)

fig.show()

payment_counts = clean_df['payment_method'].value_counts().reset_index()

fig = px.pie(
    payment_counts,
    names='payment_method',
    values='count',
    title='Payment Method Distribution'
)

fig.show()

merchant_spending = clean_df.groupby('merchant')['amount'].sum().reset_index()

fig = px.bar(
    merchant_spending,
    x='merchant',
    y='amount',
    title='Merchant-wise Spending'
)

fig.show()

time_spending = clean_df.groupby('time_period')['amount'].sum().reset_index()

fig = px.bar(
    time_spending,
    x='time_period',
    y='amount',
    title='Spending by Time of Day'
)

fig.show()

weekend_spending = clean_df.groupby('day_type')['amount'].sum().reset_index()

fig = px.bar(
    weekend_spending,
    x='day_type',
    y='amount',
    title='Weekend vs Weekday Spending'
)

fig.show()

daily_spending = clean_df.groupby('date')['amount'].sum().reset_index()

fig = px.line(
    daily_spending,
    x='date',
    y='amount',
    title='Daily Spending Trend',
    markers=True
)

fig.show()

high_spending = clean_df[clean_df['amount'] > 1000]

fig = px.bar(
    high_spending,
    x='merchant',
    y='amount',
    title='High Spending Transactions'
)

fig.show()

!pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt

pivot_table = clean_df.pivot_table(
    values='amount',
    index='day_name',
    columns='time_period',
    aggfunc='sum'
)

plt.figure(figsize=(8,5))
sns.heatmap(pivot_table, annot=True)

plt.title('Spending Heatmap')
plt.show()

clean_df['impulsive_spend'] = (
    (clean_df['hour'] >= 22) |
    (clean_df['amount'] > 700)
)

clean_df[['merchant', 'amount', 'hour', 'impulsive_spend']].head()

clean_df['impulsive_spend'].value_counts()

clean_df[clean_df['impulsive_spend'] == True]['amount'].sum()

impulsive_counts = clean_df['impulsive_spend'].value_counts().reset_index()

fig = px.pie(
    impulsive_counts,
    names='impulsive_spend',
    values='count',
    title='Impulsive Spending Distribution'
)

fig.show()

avg_spending = clean_df['amount'].mean()

high_spending_count = (
    clean_df['amount'] > 1000
).sum()

impulsive_count = (
    clean_df['impulsive_spend']
).sum()

print(avg_spending)
print(high_spending_count)
print(impulsive_count)

if (
    avg_spending > 800
    or high_spending_count > 5
    or impulsive_count > 5
):
    risk = "HIGH"

elif (
    avg_spending > 400
):
    risk = "MEDIUM"

else:
    risk = "LOW"

print("Overspending Risk:", risk)

score = 100

score -= impulsive_count * 5
score -= high_spending_count * 5

score = max(score, 0)

print("Financial Health Score:", score)

if score >= 80:
    status = "Excellent"

elif score >= 60:
    status = "Moderate"

else:
    status = "Poor"

print(status)

recommendations = []

if impulsive_count > 5:
    recommendations.append(
        "Reduce late-night spending."
    )

if high_spending_count > 3:
    recommendations.append(
        "Avoid frequent high-value purchases."
    )

if avg_spending > 700:
    recommendations.append(
        "Set a monthly spending budget."
    )

for rec in recommendations:
    print("-", rec)

clean_df.to_csv(
    'finance_project_final.csv',
    index=False
)

!pip install scikit-learn

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

ml_df = clean_df.copy()

ml_df['category'] = ml_df['category'].astype('category').cat.codes
ml_df['payment_method'] = ml_df['payment_method'].astype('category').cat.codes
ml_df['day_type'] = ml_df['day_type'].astype('category').cat.codes
ml_df['time_period'] = ml_df['time_period'].astype('category').cat.codes

X = ml_df[
    [
        'category',
        'payment_method',
        'hour',
        'day_type',
        'time_period'
    ]
]

y = ml_df['amount']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

predictions

comparison = pd.DataFrame({
    'Actual': y_test,
    'Predicted': predictions
})

comparison

error = mean_absolute_error(
    y_test,
    predictions
)

print("Mean Absolute Error:", error)

new_transaction = [[
    0,  # category
    1,  # payment method
    22, # hour
    1,  # weekday/weekend
    3   # time period
]]

prediction = model.predict(
    new_transaction
)

print(
    "Predicted Spend Amount:",
    prediction[0]
)

ml_df['overspend'] = (
    ml_df['amount'] > 1000
).astype(int)

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X = ml_df[
    [
        'category',
        'payment_method',
        'hour',
        'day_type'
    ]
]

y = ml_df['overspend']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

tree_model = DecisionTreeClassifier()

tree_model.fit(
    X_train,
    y_train
)

predictions = tree_model.predict(
    X_test
)

predictions

accuracy = accuracy_score(
    y_test,
    predictions
)

print(
    "Accuracy:",
    accuracy
)

!pip install streamlit pyngrok

!pip install streamlit-option-menu streamlit-extras

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# import numpy as np
# from streamlit_option_menu import option_menu
# 
# # ====================================
# # PAGE CONFIG
# # ====================================
# 
# st.set_page_config(
#     page_title="Finance Intelligence",
#     page_icon="💰",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# # ====================================
# # PREMIUM CSS
# # ====================================
# 
# st.markdown("""
# <style>
# 
# /* Main background */
# .stApp {
#     background-color: #F6F8FC;
# }
# 
# /* Remove default padding */
# .block-container {
#     padding-top: 2rem;
#     padding-bottom: 2rem;
#     padding-left: 3rem;
#     padding-right: 3rem;
# }
# 
# /* Sidebar */
# [data-testid="stSidebar"] {
#     background: white;
#     border-right: 1px solid #EAEAEA;
# }
# 
# /* Title */
# .main-title {
#     font-size: 42px;
#     font-weight: 700;
#     color: #111827;
# }
# 
# .subtitle {
#     color: #6B7280;
#     font-size: 16px;
#     margin-bottom: 30px;
# }
# 
# /* KPI Cards */
# .metric-card {
#     background: white;
#     border-radius: 24px;
#     padding: 25px;
#     box-shadow: 0px 8px 25px rgba(0,0,0,0.06);
#     border: 1px solid #F1F1F1;
# }
# 
# /* Insight cards */
# .insight-card {
#     background: white;
#     padding: 22px;
#     border-radius: 22px;
#     box-shadow: 0px 4px 15px rgba(0,0,0,0.05);
#     margin-bottom: 15px;
# }
# 
# /* Chart containers */
# .chart-card {
#     background: white;
#     border-radius: 24px;
#     padding: 20px;
#     box-shadow: 0px 4px 18px rgba(0,0,0,0.05);
# }
# 
# /* Recommendation box */
# .recommend-box {
#     background: linear-gradient(
#         135deg,
#         #EEF4FF,
#         #FFFFFF
#     );
# 
#     padding: 18px;
#     border-radius: 18px;
#     margin-bottom: 12px;
#     border-left: 5px solid #2563EB;
# }
# 
# </style>
# """, unsafe_allow_html=True)
# 
# # ====================================
# # HEADER
# # ====================================
# 
# st.markdown(
#     """
#     <div class='main-title'>
#     💰 Personal Finance Intelligence
#     </div>
# 
#     <div class='subtitle'>
#     AI-powered spending intelligence dashboard
#     </div>
#     """,
#     unsafe_allow_html=True
# )
# 
# # ====================================
# # SIDEBAR
# # ====================================
# 
# with st.sidebar:
# 
#     st.markdown("## Navigation")
# 
#     selected = option_menu(
#         menu_title=None,
#         options=[
#             "Overview",
#             "Analytics",
#             "Behavior",
#             "Recommendations"
#         ],
#         icons=[
#             "house",
#             "bar-chart",
#             "activity",
#             "lightbulb"
#         ],
#         default_index=0
#     )
# 
#     st.markdown("---")
# 
#     uploaded_file = st.file_uploader(
#         "Upload CSV",
#         type=["csv"]
#     )
# 
# # ====================================
# # IF NO FILE
# # ====================================
# 
# if uploaded_file is None:
# 
#     st.info(
#         "Upload a financial transaction CSV file to begin."
#     )
# 
#     st.stop()
# 
# # ====================================
# # LOAD DATA
# # ====================================
# 
# df = pd.read_csv(uploaded_file)
# 
# df.columns = (
#     df.columns
#     .str.lower()
#     .str.strip()
# )
# 
# df.drop_duplicates(inplace=True)
# 
# # Date cleaning
# if 'date' in df.columns:
#     df['date'] = pd.to_datetime(
#         df['date'],
#         errors='coerce'
#     )
# 
# # ====================================
# # FEATURES
# # ====================================
# 
# if 'hour' in df.columns:
# 
#     def spending_time(hour):
# 
#         if hour < 12:
#             return "Morning"
# 
#         elif hour < 17:
#             return "Afternoon"
# 
#         elif hour < 21:
#             return "Evening"
# 
#         return "Night"
# 
#     df['time_period'] = (
#         df['hour']
#         .apply(spending_time)
#     )
# 
# # ====================================
# # KPI VALUES
# # ====================================
# 
# total_spending = (
#     df['amount'].sum()
# )
# 
# avg_spending = (
#     df['amount'].mean()
# )
# 
# highest_expense = (
#     df['amount'].max()
# )
# 
# transaction_count = len(df)
# 
# # ====================================
# # PAGE 1 OVERVIEW
# # ====================================
# 
# if selected == "Overview":
# 
#     st.subheader("Financial Overview")
# 
#     c1, c2, c3, c4 = st.columns(4)
# 
#     c1.metric(
#         "💸 Total Spending",
#         f"₹{round(total_spending)}"
#     )
# 
#     c2.metric(
#         "📈 Avg Spend",
#         f"₹{round(avg_spending)}"
#     )
# 
#     c3.metric(
#         "🔥 Highest Expense",
#         f"₹{round(highest_expense)}"
#     )
# 
#     c4.metric(
#         "🧾 Transactions",
#         transaction_count
#     )
# 
#     st.markdown("### Dataset Preview")
# 
#     st.dataframe(
#         df.head(10),
#         use_container_width=True
#     )
# 
# # ====================================
# # ANALYTICS PAGE
# # ====================================
# 
# elif selected == "Analytics":
# 
#     st.subheader(
#         "Spending Analytics"
#     )
# 
#     col1, col2 = st.columns(2)
# 
#     if 'category' in df.columns:
# 
#         category_data = (
#             df.groupby('category')
#             ['amount']
#             .sum()
#             .reset_index()
#         )
# 
#         fig1 = px.bar(
#             category_data,
#             x='category',
#             y='amount',
#             title="Category Spending"
#         )
# 
#         col1.plotly_chart(
#             fig1,
#             use_container_width=True
#         )
# 
#     if 'merchant' in df.columns:
# 
#         merchant_data = (
#             df.groupby('merchant')
#             ['amount']
#             .sum()
#             .reset_index()
#             .sort_values(
#                 by='amount',
#                 ascending=False
#             )
#             .head(10)
#         )
# 
#         fig2 = px.bar(
#             merchant_data,
#             x='merchant',
#             y='amount',
#             title="Top Merchants"
#         )
# 
#         col2.plotly_chart(
#             fig2,
#             use_container_width=True
#         )
# 
#     if 'date' in df.columns:
# 
#         daily = (
#             df.groupby('date')
#             ['amount']
#             .sum()
#             .reset_index()
#         )
# 
#         fig3 = px.line(
#             daily,
#             x='date',
#             y='amount',
#             markers=True,
#             title="Daily Spending Trend"
#         )
# 
#         st.plotly_chart(
#             fig3,
#             use_container_width=True
#         )
# 
# # ====================================
# # BEHAVIOR PAGE
# # ====================================
# 
# elif selected == "Behavior":
# 
#     st.subheader(
#         "Behavioral Analytics"
#     )
# 
#     if 'hour' in df.columns:
# 
#         df['impulsive'] = (
#             (df['hour'] >= 22)
#             |
#             (df['amount'] > 700)
#         )
# 
#         impulsive_count = (
#             df['impulsive']
#             .sum()
#         )
# 
#         st.metric(
#             "⚠️ Impulsive Purchases",
#             impulsive_count
#         )
# 
#         fig4 = px.pie(
#             df,
#             names='impulsive',
#             title="Impulsive Spending"
#         )
# 
#         st.plotly_chart(
#             fig4,
#             use_container_width=True
#         )
# 
# # ====================================
# # RECOMMENDATIONS
# # ====================================
# 
# elif selected == "Recommendations":
# 
#     st.subheader(
#         "Smart Recommendations"
#     )
# 
#     recommendations = []
# 
#     if avg_spending > 700:
# 
#         recommendations.append(
#             "💡 Your spending is relatively high. Consider setting a monthly spending cap."
#         )
# 
#     if 'merchant' in df.columns:
# 
#         top_merchant = (
#             df.groupby('merchant')
#             ['amount']
#             .sum()
#             .idxmax()
#         )
# 
#         recommendations.append(
#             f"🛍️ Highest spending occurs at {top_merchant}. Consider monitoring expenses there."
#         )
# 
#     if len(recommendations) == 0:
# 
#         st.success(
#             "Healthy spending pattern detected."
#         )
# 
#     else:
# 
#         for rec in recommendations:
# 
#             st.markdown(
#                 f"""
#                 <div class='recommend-box'>
#                 {rec}
#                 </div>
#                 """,
#                 unsafe_allow_html=True
#             )

!pip install streamlit plotly

!streamlit run app.py & npx localtunnel --port 8501